create database Product_Sale;
use product_Sale;

--  1: How many orders has each customer placed?
SELECT Customer_ID,
       COUNT(Order_ID) AS Total_Orders
FROM Orders
GROUP BY Customer_ID;

-- 2: What is the total quantity sold for each product?
SELECT Product_ID,
       SUM(Quantity) AS Total_Quantity
FROM Orders
GROUP BY Product_ID;

-- 3: How many customers belong to each city?
SELECT City,
       COUNT(Customer_ID) AS Total_Customers
FROM Customers
GROUP BY City;

-- 4: How many customers are loyalty members?
SELECT Loyalty_Member,
       COUNT(*) AS Total_Customers
FROM Customers
GROUP BY Loyalty_Member;

-- 5: Which payment methods are used most frequently?
SELECT Payment_Method,
       COUNT(*) AS Total_Transactions
FROM Orders
GROUP BY Payment_Method
ORDER BY Total_Transactions DESC;

--6: What is the total revenue generated by each product?
SELECT
    p.Product_Name,
    SUM(o.Quantity * p.Price) AS Revenue
FROM Orders o
JOIN Products p
ON o.Product_ID = p.Product_ID
GROUP BY p.Product_Name
ORDER BY Revenue DESC;

-- 7: Which products are ordered most frequently?
SELECT
    p.Product_Name,
    COUNT(o.Order_ID) AS Total_Orders
FROM Orders o
JOIN Products p
ON o.Product_ID = p.Product_ID
GROUP BY p.Product_Name
ORDER BY Total_Orders DESC;

--8: What is the total revenue generated by each category?
SELECT
    p.Category,
    SUM(o.Quantity * p.Price) AS Revenue
FROM Orders o
JOIN Products p
ON o.Product_ID = p.Product_ID
GROUP BY p.Category
ORDER BY Revenue DESC;

--9: Which customers have placed the highest number of orders?
SELECT
    c.Customer_ID,
    COUNT(o.Order_ID) AS Total_Orders
FROM Customers c
JOIN Orders o
ON c.Customer_ID = o.Customer_ID
GROUP BY c.Customer_ID
ORDER BY Total_Orders DESC;

--10: Which cities generate the highest revenue?
SELECT
    c.City,
    SUM(o.Quantity * p.Price) AS Revenue
FROM Customers c
JOIN Orders o
ON c.Customer_ID = o.Customer_ID
JOIN Products p
ON o.Product_ID = p.Product_ID
GROUP BY c.City
ORDER BY Revenue DESC;

--11: What is the average age of customers in each city?
SELECT City, ROUND(AVG(Age),2) AS Average_Age
FROM Customers
GROUP BY City;

--12: Which product categories are purchased the most?
SELECT
    p.Category,
    SUM(o.Quantity) AS Total_Quantity
FROM Orders o
JOIN Products p
ON o.Product_ID = p.Product_ID
GROUP BY p.Category
ORDER BY Total_Quantity DESC;

--13: Which loyalty members generate the highest revenue?
SELECT
    c.Loyalty_Member,
    SUM(o.Quantity * p.Price) AS Revenue
FROM Customers c
JOIN Orders o
ON c.Customer_ID = o.Customer_ID
JOIN Products p
ON o.Product_ID = p.Product_ID
GROUP BY c.Loyalty_Member;

--14: What is the average order value for each customer?
SELECT
    c.Customer_ID,
    ROUND(AVG(o.Quantity * p.Price),2) AS Avg_Order_Value
FROM Customers c
JOIN Orders o
ON c.Customer_ID = o.Customer_ID
JOIN Products p
ON o.Product_ID = p.Product_ID
GROUP BY c.Customer_ID;

--15: Which products have never been ordered?
SELECT
    p.Product_Name
FROM Products p
LEFT JOIN Orders o
ON p.Product_ID = o.Product_ID
WHERE o.Order_ID IS NULL;

--16: Which products are priced above the average product price?
SELECT
    Product_Name,
    Price
FROM Products
WHERE Price >
(
    SELECT AVG(Price)
    FROM Products
);

--17: Which customers placed more orders than the average customer?
SELECT
    Customer_ID,
    COUNT(Order_ID) AS Total_Orders
FROM Orders
GROUP BY Customer_ID
HAVING COUNT(Order_ID) >
(
    SELECT AVG(Order_Count)
    FROM
    (
        SELECT COUNT(Order_ID) AS Order_Count
        FROM Orders
        GROUP BY Customer_ID
    ) AS AvgTable
);

--18: Which category generates the highest revenue?
SELECT
    Category,
    Revenue
FROM
(
    SELECT
        p.Category,
        SUM(o.Quantity * p.Price) AS Revenue
    FROM Orders o
    JOIN Products p
    ON o.Product_ID = p.Product_ID
    GROUP BY p.Category
) AS CategoryRevenue
ORDER BY Revenue DESC
LIMIT 1;

--19: Which month had the highest sales for each products?.
SELECT p.Product_Name,
MONTH(o.Order_Date) as Order_Month,
SUM(o.Quantity) as Total_Quantity
FROM Orders o
JOIN Products p
ON o.Product_ID = p.Product_ID
GROUP BY p.Product_Name, Order_Month
ORDER BY Total_Quantity DESC;

--20: Which customer generated the highest revenue?
SELECT
    c.Customer_ID,
    SUM(o.Quantity * p.Price) AS Revenue
FROM Customers c
JOIN Orders o
ON c.Customer_ID = o.Customer_ID
JOIN Products p
ON o.Product_ID = p.Product_ID
GROUP BY c.Customer_ID
ORDER BY Revenue DESC
LIMIT 1;
